config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian], allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy!
    redirect_to restaurants_path
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f|%>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :category %>
<%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<ul>
<% @restaurants.each do |restaurant| %>
    <li><%=link_to restaurant.name, restaurant_path(restaurant)%>, <%= restaurant.address%>, <%= restaurant.category%></li>
<% end %>
</ul>
<br>
<%= link_to "Add restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name%></h1>
<h2>Description</h2>
<%= @restaurant.address%><br>
<%= @restaurant.category%>
<br>
<h2>Reviews</h2>
<% if @restaurant.reviews.length.zero? %>
       <p>No reviews available.</p>
<% else %>
<%     @restaurant.reviews.each do |review| %>
           <%= review.content %><br>
           Rating: <strong><%= review.rating %></strong><br><br>
        <% end %>
<% end %>
<%= link_to "Add review", new_restaurant_review_path(@restaurant)%><br>
<%= link_to "Edit restaurant", edit_restaurant_path(@restaurant)%><br>
<%= link_to "Delete restaurant",
            restaurant_path(@restaurant),
            method: :delete %><br>
<%= link_to "Overview", restaurants_path %>

app/views/reviews/new.html.erb
<h1>Add new review</h1>
<%= simple_form_for [ @restaurant, @review ] do |f|%>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit %>
<% end %>